#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: caddy-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: caddy
#  template:
#    metadata:
#      labels:
#        app: caddy
#    spec:
#      containers:
#      - name: caddy
#        image: miuler/arch-caddy:latest
#        ports:
#        - containerPort: 8080
#
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: caddy-statefulset
spec:
  serviceName: "caddy"
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: miuler/arch-caddy:latest
        ports:
        - containerPort: 8080
  volumeClaimTemplates:
  - metadata:
      name: caddy-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi


